slack:
  app_id: A0860L8F87R
  date_of_app_creation: "December 24, 2024"
  webhook_url: "https://hooks.slack.com/services/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"
  app_manifest:
    display_information:
      name: "Lookernomicon"
      description: "AI-Grimoire for Looker Nerds"
      background_color: "#19171a"
      long_description: >
        Lookernomicon is an AI-powered comprehensive resource for Looker professionals,
        combining cutting-edge technology with expert knowledge. It offers in-depth
        LookML guides, advanced data modeling techniques, and BI strategy insights.
        Featuring a rich repository of scripts, tutorials, and best practices,
        Lookernomicon caters to both novice and experienced Looker users. With its
        integrated platform spanning documentation, community forums, and personalized
        learning paths, it accelerates mastery of Looker's capabilities.
        Lookernomicon is the go-to solution for elevating Looker implementations
        and driving data-driven decision-making across organizations.
    features:
      bot_user:
        display_name: "Lookernomicon"
        always_online: true
    oauth_config:
      scopes:
        bot:
          - incoming-webhook
    settings:
      org_deploy_enabled: false
      socket_mode_enabled: false
      token_rotation_enabled: false